// ============================================================
//  MysteryRoomResolver.cs
//  Resolves a Mystery room's actual content when the player
//  steps inside. The outcome is hidden from the player during
//  navigation and only revealed at the moment of entry.
//
//  This is intentionally a separate class from NavigationSystem
//  because the resolution happens at a different time:
//    NavigationSystem → generates choices (room type is Mystery)
//    MysteryRoomResolver → resolves content when player enters
// ============================================================

using System.Collections.Generic;
using UnityEngine;

namespace CardGame
{
    public class MysteryRoomResolver
    {
        private FloorConfig _config;

        public MysteryRoomResolver(FloorConfig config)
        {
            _config = config;
        }

        public void SetConfig(FloorConfig config) => _config = config;

        // ----------------------------------------------------------
        // Entry point — call this when the player enters a Mystery room
        // ----------------------------------------------------------

        /// <summary>
        /// Resolves a Mystery RoomChoice into its actual content.
        /// Mutates the choice in-place: sets MysteryOutcome, Enemies, and Event.
        /// Returns the outcome so RunManager knows what scene/UI to load.
        /// </summary>
        public MysteryOutcome Resolve(RoomChoice choice)
        {
            if (choice.RoomType != RoomType.Mystery)
            {
                Debug.LogWarning("[MysteryRoomResolver] Called on a non-mystery room.");
                return MysteryOutcome.Event;
            }

            MysteryOutcome outcome = _config.RollMysteryOutcome();
            choice.MysteryOutcome = outcome;

            switch (outcome)
            {
                case MysteryOutcome.Event:
                    choice.Event = _config.RollEvent();
                    break;

                case MysteryOutcome.NormalCombat:
                    var enemies = _config.RollNormalEnemies();
                    foreach (var e in enemies) choice.Enemies.Add(e);
                    break;

                case MysteryOutcome.Shop:
                    // No content to pre-roll — shop is generated by ShopManager
                    break;
            }

            return outcome;
        }

        // ----------------------------------------------------------
        // Converts a resolved Mystery into the effective RoomType
        // that RunManager should treat it as
        // ----------------------------------------------------------

        public static RoomType ToEffectiveRoomType(MysteryOutcome outcome) => outcome switch
        {
            MysteryOutcome.Event        => RoomType.Mystery,    // Stays as Mystery for UI label
            MysteryOutcome.NormalCombat => RoomType.NormalCombat,
            MysteryOutcome.Shop         => RoomType.Shop,
            _                           => RoomType.Mystery
        };
    }
}
